
import 'package:get/get.dart';

class MyLocal extends Translations{
  @override
  Map<String , Map<String, String>> get keys => {
    "ar": {
      "choose language" : "اختر لغة ",
      "Big Kitchen Burger":"بيق كيتشن برجر ",
      "Make an order of any food of choice":"اطلب طعاماً من إختيارك",
      "Login":"تسجيل الدخول",
      "Sign Up":"إشتراك",
      "Forgot your password?":"نسيت رمز الدخول؟",
      "don't have an account?":"لا تملك حساب؟",
      "At your Dinning Table":"على مائدة طعامك",
      "OTP":"كود",
      "Forgot password":"نسيت الرمز",
      "Please, enter your phone number ":"رجاءً, ادخل رقم هاتفك ",
      "Send":"ارسل",
      "Please, enter OTP code":"رجاءً, أدخل الكود",
      "Favorites":"المفضلات",
      "All":"الكل",
      "Burgers":"برجر",
      "Pizza":"بيتزا",
      "Filters":"تصفية",

      "Price: lowest to high":"السعر: من الأقل للأكثر",
      "Beef Juicy Burger":"برجر لحم بقر",
      "Components":"المكونات",
      "Place Order":"أتم الطلب",
      "Apply":"تطبيق",
      "Descripion":"الوصف",
      "Size info":"معلومات الحجم",
      "Select size":"اختيار الحجم",
      "Size":"الحجم",
      "Buy Now":"أشتري الآن",

      "Juice":"عصير",
      "Bread":", خبز",
      "Lets eat Something":"لنأكل شيئًا ما",
      "Delicious":"لذيذ",
      "Beef":"لحم بقر",
      "Cheese":"جبنة",
      "Fries":"بطاطس",

      "Side Salad":"سلطة جانبية",
      "Ketchup":"كاتشب",
      "Coca-Cola":"كوكاكولا",
      "Discard":"تجاهل",
      "My Cart":"سلتي",
      "Check Out":"الدفع",
      "Your Promo Codes":"الرموز الترويجية الخاصة بك",
      "Personal Offer":"عرض شخصي",
      "Summer Sale":"تخفيضات الصيف",
      "In Restaurant":"في المطعم",
      "Delivery":"توصيل",
      "Addresses":"العناوين",
      "Edit":"تعديل",
      "Use as the shipping address":"أستخدم كعنوان الشحن",
      "Adding Address":"أضف عنوان",
      "Save Address":"حفظ العنوان",
      "Cash":"نقد",
      "Payment Card":"بطاقة الدفع",
      "Settings":"الإعدادات",
      "Personal Information":"معلومات شخصية",
      "Password":"كلمة السر",
      "Password Change":"تغيير كلمة السر",
      "Save Password":"حفظ كلمة السر",
      "My Orders":"طلباتي",
      "My profile":"ملفي الشخصي",
      "Payment methods":"طرق الدفع",
      "Promocodes":"أكواد الخصم",
      "My reviews":"تقييماتي",
      "Light":"فاتح",

      "Success":"تم",
      "Your order will be delivered soon. Thank you for choosing our app!":"سيتم تسليم طلبك قريبًا. شكرًا لإختيارك تطبيقنا! ",
      "Home":"الصفحة الرئيسية",
      "Total Products ":"إجمالي المنتجات",
      "Total Amount ":"المبلغ الإجمالي",
      "Delivery  Time":"وقت التوصيل",
      "Confirm ":"تأكيد",
      "Add new card":"إضافة بطاقة دفع جديدة",
      "Add Card":"إضافة البطاقة",
      "Your payment cards":"بطاقات الدفع الخاصة بك",
      "Delivered":"تم التوصيل",
      "Processing":"تحت التجهيز",
      "Canceled":"تم الإلغاء",
      "Order No":"رقم الطلب",
      "Details":"االتفاصيل",
      "items":"عناصر",
      "Order information":"معلومات الطلب",
      "Kitchen":" المطبخ",
      "Reorder":"إعادة الطلب",

      "Confirmed Order":"تأكيد الطلب",
      "in kitchen":"في المطبخ",
      "Delivery Order":"تسليم الطلب",
      "The order has been delivered":"تم تسليم الطلب!",
      "Cancel":"الغاء",
      "Delete":"حذف",
      "Completed":"مكتمل",
      "You're now online":"انت متصل الآن",
      "Accept":"قبول",



    },

    "en" :{
      "CHOOSE LANGUAGE" : "choose language",
      "BIG KITCHEN BURGER":"Big Kitchen Burger",
      "MAKE AN ORDER OF ANY FOOD OF CHOICE":"Make an order of any food of choice",
      "LOGIN":"Login",
      "SIGN UP":"Sign Up",
      "FORGOT YOUR PASSWORD?":"Forgot your password?",
      "DON'T HAVE AN ACCOUNT?":"don't have an account?",
      "AT YOUR DINING TABLE":"At your Dinning Table",
      "OTP":"OTP",
      "FORGOT PASSWORD":"Forgot password",
      "PLEASE, ENTER YOUR PHONE NUMBER":"Please, enter your phone number",
      "SEND":"Send",
      "PLEASE, ENTER OTP CODE":"Please, enter OTP code",
      "FAVORITES":"Favorites",
      "ALL":"All",
      "BURGERS":"Burgers",
      "PIZZA":"Pizza",
      "FILTERS":"Filters",
      "PRICE: LOWEST TO HIGH":"Price: lowest to high",
      "BEEF JUICY BURGER":"Beef Juicy Burger",
      "COMPONENTS":"Components",
      "PLACE ORDER":"Place Order",
      "APPLY":"Apply",
      "DESCRIPTION":"Descripion",
      "SIZE INFO ":"Size info",
      "SELECT SIZE":"Select size",
      "SIZE ":"Size",
      "BUY NOW":"Buy Now",
      "JUICE":"Juice",
      "BREAD":"Bread",
      "LETS EAT SOMETHING":"Lets eat Something",
      "DELICIOUS":"Delicious",
      "BEEF":"Beef",
      "CHEESE":"Cheese",
      "FRIES":"Fries",
      "SIDE SALAD":"Side Salad",
      "KETCHUP":"Ketchup",
      "COCA-COLA":"Coca-Cola",
      "DISCARD":"Discard",
      "MY CART":"My Cart",
      "CHECK OUT":"Check Out",
      "YOUR PROMO CODES":"Your Promo Codes",
      "PERSONAL OFFER":"Personal Offer",
      "SUMMER SALE":"Summer Sale",
      "IN RESTAURANT":"In Restaurant",
      "DELIVERY":"Delivery",
      "ADDRESSES":"Addresses",
      "EDIT":"Edit",
      "USE AS THE SHIPPING ADDRESS":"Use as the shipping address",
      "ADDING ADDRESS":"Adding Address",
      "SAVE ADDRESS":"Save Address",
      "CASH":"Cash",
      "PAYMENT CARD":"Payment Card",
      "SETTINGS":"Settings",
      "PERSONAL INFORMATION":"Personal Information",
      "PASSWORD":"Password",
      "PASSWORD CHANGE":"Password Change",
      "SAVE PASSWORD":"Save Password",
      "MY ORDERS":"My Orders",
      "MY PROFILE":"My profile",
      "PAYMENT METHODS":"Payment methods",
      "PROMOCODES":"Promocodes",
      "MY REVIEWS":"My reviews",
      "LIGHT":"Light",
      "SUCCESS":"Success",
      "YOUR ORDER WILL BE DELIVERED SOON. THANK YOU FOR CHOOSING OUR APP!":"Your order will be delivered soon. Thank you for choosing our app!",
      "HOME":"Home",
      "TOTAL PRODUCTS":"Total Products",
      "TOTAL AMOUNT":"Total Amount",
      "DELIVERY TIME":"Delivery  Time",
      "CONFIRM":"Confirm ",
      "ADD NEW CARD":"Add new card",
      "ADD CARD":"Add Card",
      "YOUR PAYMENT CARDS":"Your payment cards",
      "DELIVERED":"Delivered",
      "PROCESSING":"Processing",
      "CANCELED":"Canceled",
      "ORDER NO":"Order No",
      "DETAILS":"Details",
      "ITEMS":"items",
      "ORDER INFORMATION":"Order information",
      "KITCHEN":"Kitchen",
      "REORDER":"Reorder",
      "CONFIRMED ORDER":"Confirmed Order",
      "IN KITCHEN":"in kitchen",
      "DELIVERY ORDER":"Delivery Order",
      "THE ORDER HAS BEEN DELIVERED":"The order has been delivered",
      "CANCEL":"Cancel",
      "DELETE":"Delete",
      "COMPLETED":"Completed",
      "YOU'RE NOW ONLINE":"You're now online",
      "ACCEPT":"Accept",
     

    }
  } ;
}